### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://192.168.100.241:8082/xxl-job-admin
      #addresses: http://localhost:8080/xxl-job-admin

    ### xxl-job executor address
    executor:
      appname: cloud-coupon-server
      ip:
      port: 9999
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1

    ### xxl-job, access token
    accessToken: